### PR TITLE
chore!: adopt log/slog, drop go-kit/log

### PR DESCRIPTION
**Pull request by tjhop**
The bulk of this change set was automated by the following script which
is being used to aid in converting the various exporters/projects to use
slog:

https://gist.github.com/tjhop/49f96fb7ebbe55b12deee0b0312d8434

In addition to the parts that were straightforward conversions, this
also:
- refactors much of the logging config to adopt slog
    - removed custom `logger.go` setup for go-kit
    - adopt promslog/flag and use that to handle parsing log
      level/format flags
    - for consistent behavior, keep log output flag to allow toggle
      stdout/stderr for output
    - adopt promslog for logger setup
- enables sloglint in golangci-lint config
- drops go-kit/log exclusions from lint config
- tidies mods to drop go-kit/log and go-logfmt/logfmt deps

### CODE REVIEW

**Comment by tjhop** [comment]
cc: @SuperQ

**Comment by SuperQ** [comment]
Same here, just needs a rebase for the linter.

**Comment by tjhop** [comment]
Rebased 👍

**Review by sysadmind — APPROVED** [review]
LGTM

**Pull request merged**
