### PR TITLE
Basic auth for the /metrics endpoint

### PR DESCRIPTION
**Pull request by msirovy**
It is small improvement, but it could help simplify life. Please take a look and give me a feedback or simple improve it.

### CODE REVIEW

**Comment by sysadmind** [comment]
Basic auth should be handled by the exporter-toolkit instead of a custom implementation. 

See here: https://github.com/prometheus/exporter-toolkit/tree/master/web

**Comment by msirovy** [comment]
Nice. I've missed it. You don't have mentioned it in the documentation. The flag for enabling base auth is 

```bash
--web.config.file=path.yaml
```

**Comment by sysadmind** [comment]
@msirovy I assume that means this PR can be closed?

**Comment by msirovy** [comment]
Closing

**Comment by msirovy** [comment]
Ive found one problem. latest release in this repository does NOT contain this flag. It seems to me like you don't release new package for a long time.

**Pull request closed without merging**
