### PR TITLE
Cluster health refactor

### PR DESCRIPTION
**Pull request by sysadmind**
Followup to #521 

Work to refactor the cluster health exporter

### CODE REVIEW

**Comment by gaima8** [comment]
Hey @sysadmind 
Would you mind, if possible, adding active_shards_percent_as_number too?

**Comment by sysadmind** [comment]
@gaima8 This can already be calculated from the other metrics. According to the prometheus docs, it's best not to export percentages, but rather calculate those at query time. https://prometheus.io/docs/instrumenting/writing_exporters/#naming

**Comment by sysadmind** [comment]
@SuperQ This is ready for review now.

**Comment by SuperQ** [comment]
It looks like this needs a rebase.

**Pull request closed without merging**
