### PR TITLE
Allow to specify ES_USERNAME/ES_PASSWORD environment variables to connect to the ES node

### PR DESCRIPTION
**Pull request by guillaumelecerf**

### CODE REVIEW

**Comment by guillaumelecerf** [comment]
Arg, seems duplicating https://github.com/prometheus-community/elasticsearch_exporter/pull/308

**Comment by guillaumelecerf** [comment]
To address [this comment](https://github.com/prometheus-community/elasticsearch_exporter/pull/308#pullrequestreview-672305330), I change my approach to only accept credentials from the environment variables.

**Review by sysadmind — APPROVED** [review]
LGTM

**Comment by guillaumelecerf** [comment]
Thanks @sysadmind !

**Pull request merged**
