### PR TITLE
feat: go.mod and dep updates 

### PR DESCRIPTION
**Pull request by caarlos0**
switch to go modules and updated all deps.

### CODE REVIEW

**Comment by sysadmind** [comment]
I think the .promu.yml file needs to change as well to not use the `{{repopath}}/vendor` prefix anymore. You can take a look at the changes I had in #333

**Comment by caarlos0** [comment]
Done, thanks @sysadmind :)

**Comment by dsabsay** [comment]
Can this be merged? What's holding it up (can I help)?

**Comment by SuperQ** [comment]
This was completed in https://github.com/prometheus-community/elasticsearch_exporter/pull/420

**Pull request closed without merging**
