### PR TITLE
Update README docker image references

### PR DESCRIPTION
**Pull request by sysadmind**
Signed-off-by: Joe Adams <github@joeadams.io>

### CODE REVIEW

**Comment by ustuzhanin** [comment]
Please set correct link
```
docker pull quay.io/prometheuscommunity/elasticsearch_exporter:1.2.0
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

```
docker pull quay.io/prometheuscommunity/elasticsearch-exporter:v1.2.0
v1.2.0: Pulling from prometheuscommunity/elasticsearch-exporter
11b2a01e7371: Pull complete
aac1165536db: Pull complete
340b721a0dc5: Pull complete
Digest: sha256:52b3afb0e8033d5d30e330aca9baa07451bde6a7d6f4333ae11ca5fc3f2d4df8
Status: Downloaded newer image for quay.io/prometheuscommunity/elasticsearch-exporter:v1.2.0
quay.io/prometheuscommunity/elasticsearch-exporter:v1.2.0
```

**Comment by SuperQ** [comment]
The readme should probably reference `latest`, rather than a specific tag.

**Comment by caarlos0** [comment]
> The readme should probably reference `latest`, rather than a specific tag.

Agreed...

**Comment by sysadmind** [comment]
I updated the image name. Thanks @ustuzhanin for that catch. 
I also updated the tag to latest. I'm not sure that latest is the best choice because it is based on the master branch and there will very likely be breaking changes as we move towards a 2.0 release, but it also means that we don't have to change this with every release.

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by SuperQ** [comment]
`latest` is not based on the master branch, it's based on the release. The `master` tag is what is pushed for every commit.

**Comment by SuperQ** [comment]
See: https://quay.io/repository/prometheuscommunity/elasticsearch-exporter?tab=tags

v1.2.0 matches lastest sha256

**Comment by sysadmind** [comment]
I stand corrected! Thanks!

**Pull request merged**
